name: killtheplayer-plugin
description: it adds a command that... kills you
version: '1.0'
main: fi.assyt.kysplugin.MainClass
api-version: '1.16'
commands:
  kys:
    description: it... kills you
    usage: /<command>